server:
  port: 8080

# 数据库数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
<<<<<<< HEAD
    password: root
    url: jdbc:mysql://localhost:3306/city_1?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
=======
    password: 
    url: jdbc:mysql://localhost:3306/city?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&allowMultiQueries=true
>>>>>>> 8f87818c1007169ad8fc5bcd4ca61d6199f9af37
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: yjp.pojo   #   别名
  mapper-locations: classpath:/mybatis/*.xml   #   xml文件

logging:
  file:
    name: log/log.log
  level:
    root: info
    yjp: debug
